/*
 * Recipe data. Every recipe makes 4 servings = dinner for 2 + one round of leftovers.
 *
 * Ingredient fields:
 *   q    quantity (number, or null for "to taste"/"as desired")
 *   u    unit (singular: lb, oz, cup, tbsp, tsp, clove, can, jar, slice) or "" for a count
 *   sz   package size shown in parentheses, e.g. "15 oz"
 *   n    item name (singular for counted items); used as the shopping-list key
 *   pl   plural name for counted items when it isn't just n + "s"
 *   prep how to prep it (recipe view only)
 *   a    grocery aisle
 *   gf   true = must carry a gluten-free label / needs a label check
 *   opt  optional
 *
 * Recipe `source` = a published recipe this one was checked against (timings/method), plus how ours differs.
 */

const AISLES = [
  "Produce",
  "Meat",
  "Dairy",
  "Canned & jarred",
  "Sauces & condiments",
  "Rice, pasta & grains",
  "Spices & baking",
  "Frozen",
  "Bread & tortillas",
  "Staples (you probably have these)",
];

const P = "Produce", M = "Meat", D = "Dairy", C = "Canned & jarred", S = "Sauces & condiments",
  G = "Rice, pasta & grains", SP = "Spices & baking", F = "Frozen", B = "Bread & tortillas",
  ST = "Staples (you probably have these)";

const RECIPES = [
  // ───────────────────────────── COMFORT ─────────────────────────────
  {
    id: "pot-roast",
    source: { name: "Kristine's Kitchen", url: "https://kristineskitchenblog.com/instant-pot-pot-roast/", note: "Same method (60 min for halved chuck, then veg 5 min, cornstarch gravy). Theirs is 3 lb / 8 servings." },
    title: "Classic Pot Roast & Gravy",
    cuisine: "Comfort",
    blurb: "Fork-tender chuck roast, potatoes and carrots, with a gravy thickened with cornstarch instead of flour.",
    best: "Either",
    prep: "20 min",
    ipTotal: "~1 hr 50 min",
    scTotal: "8–9 hr on low",
    gf: [
      "Beef broth: buy one labeled gluten free. Some broths and bouillons contain wheat or barley.",
      "Worcestershire: Lea & Perrins sold in the US is labeled GF. The UK/Canadian version uses malt vinegar (barley), so it is not safe.",
      "Thicken the gravy with cornstarch. Never use all-purpose flour.",
    ],
    ingredients: [
      { title: "", items: [
        { q: 2.5, u: "lb", n: "boneless beef chuck roast", a: M },
        { q: 1, u: "lb", n: "baby gold potatoes", prep: "halved if large", a: P },
        { q: 4, u: "", n: "carrot", prep: "cut in 2-inch chunks", a: P },
        { q: 1, u: "", n: "yellow onion", prep: "cut in wedges", a: P },
        { q: 4, u: "clove", n: "garlic", prep: "minced", a: P },
        { q: 1.5, u: "cup", n: "beef broth", gf: true, a: C },
        { q: 2, u: "tbsp", n: "tomato paste", a: C },
        { q: 1, u: "tbsp", n: "Worcestershire sauce", gf: true, a: S },
        { q: 1, u: "tsp", n: "dried thyme", a: SP },
        { q: 2, u: "tbsp", n: "cornstarch", a: SP },
        { q: 1, u: "tbsp", n: "olive oil", a: ST },
        { q: 2, u: "tsp", n: "kosher salt", a: ST },
        { q: 1, u: "tsp", n: "black pepper", a: ST },
      ]},
    ],
    ip: [
      "Pat the roast dry, cut it into 2–3 large chunks, and season all over with the salt and pepper.",
      "Set to Sauté (High/More). Add oil and sear the beef 3–4 min per side until well browned. Work in batches if needed, then set aside.",
      "Add the onion and cook 2 min. Stir in the garlic and tomato paste for 1 min.",
      "Pour in the broth and Worcestershire, then <strong>scrape every browned bit off the bottom</strong>. This prevents the Burn notice.",
      "Return the beef and its juices and sprinkle with thyme. Seal and cook on <strong>High Pressure 60 min</strong>, then <strong>natural release 15 min</strong>.",
      "Open the lid, nestle the potatoes and carrots around the beef, and cook on <strong>High Pressure 5 min</strong>, then quick release.",
      "Move the beef and vegetables to a platter. Set to Sauté, whisk the cornstarch with 3 tbsp cold water, stir it into the liquid, and simmer 1–2 min until it becomes gravy.",
    ],
    sc: [
      "Season the roast with salt and pepper. For much deeper flavor, sear it in a hot oiled skillet 3–4 min per side. This step is optional.",
      "Put the potatoes, carrots and onion in the bottom of the slow cooker and set the beef on top.",
      "Whisk the broth, Worcestershire, tomato paste, garlic and thyme together and pour over.",
      "Cook on <strong>low 8–9 hr</strong> (or high 5–6 hr) until the beef pulls apart easily.",
      "Pour the liquid into a saucepan, bring it to a simmer, and stir in the cornstarch whisked with 3 tbsp cold water. Simmer 1–2 min to thicken.",
    ],
    serve: "Serve as is. It's a complete meal.",
    leftovers: "Shred the leftover beef onto GF bread with the gravy, or crisp it in a skillet with the potatoes for hash.",
  },

  {
    id: "chicken-wild-rice-soup",
    source: { name: "Little Spice Jar", url: "https://www.littlespicejar.com/instant-pot-chicken-wild-rice-soup/", note: "Theirs cooks pure wild rice 35 min and thickens with a <strong>flour roux</strong>. Ours uses cornstarch + cream instead." },
    title: "Creamy Chicken & Wild Rice Soup",
    cuisine: "Comfort",
    blurb: "A cozy, creamy soup thickened with cornstarch, not a roux. The wild rice holds up well for next-day lunch.",
    best: "Instant Pot",
    prep: "15 min",
    ipTotal: "~1 hr",
    scTotal: "6–7 hr on low",
    gf: [
      "Use <strong>plain wild rice or a plain wild rice blend</strong>. Boxed \"long grain & wild rice\" mixes often have wheat in the seasoning packet.",
      "Chicken broth: must be labeled GF.",
    ],
    ingredients: [
      { title: "", items: [
        { q: 1.25, u: "lb", n: "boneless skinless chicken thighs", a: M },
        { q: 1, u: "", n: "yellow onion", prep: "diced", a: P },
        { q: 2, u: "", n: "carrot", prep: "diced", a: P },
        { q: 2, u: "", n: "celery stalk", prep: "diced", a: P },
        { q: 3, u: "clove", n: "garlic", prep: "minced", a: P },
        { q: 0.75, u: "cup", n: "wild rice (plain)", prep: "rinsed", gf: true, a: G },
        { q: 5, u: "cup", n: "chicken broth", gf: true, a: C },
        { q: 1, u: "tsp", n: "dried thyme", a: SP },
        { q: 1, u: "", n: "bay leaf", pl: "bay leaves", a: SP },
        { q: 1, u: "cup", n: "heavy cream", a: D },
        { q: 2, u: "tbsp", n: "cornstarch", a: SP },
        { q: 2, u: "tbsp", n: "butter", a: D },
        { q: 1, u: "tsp", n: "kosher salt", a: ST },
        { q: 0.5, u: "tsp", n: "black pepper", a: ST },
      ]},
    ],
    ip: [
      "Set to Sauté. Melt the butter and cook the onion, carrot and celery 3–4 min. Add the garlic for 30 sec.",
      "Pour in the broth and scrape the bottom clean.",
      "Add the rinsed wild rice, thyme, bay leaf, salt and pepper, and lay the chicken on top.",
      "Seal and cook on <strong>High Pressure 30 min</strong>, then <strong>natural release 10 min</strong>.",
      "Remove the chicken, shred it with two forks, and discard the bay leaf.",
      "Set to Sauté. Whisk the cream and cornstarch together, stir into the soup, and simmer 2–3 min until thickened. Return the chicken and adjust the salt.",
    ],
    sc: [
      "Add everything except the cream and cornstarch to the slow cooker. Sautéing the vegetables in butter first is optional.",
      "Cook on <strong>low 6–7 hr</strong> (or high 3–4 hr) until the rice has split open and is tender.",
      "Remove the chicken, shred it, and discard the bay leaf.",
      "Whisk the cream and cornstarch together, stir in with the chicken, and cook on high 15–20 min until thickened.",
    ],
    serve: "Great on its own. Add a green salad if you want more on the plate.",
    leftovers: "The rice keeps absorbing liquid, so thin leftovers with a splash of broth when you reheat.",
  },

  {
    id: "bbq-pulled-pork",
    source: { name: "Foodess", url: "https://foodess.com/instant-pot-pulled-pork/", note: "Same timing (4 chunks, 60 min + 15 min natural release; slow cooker 8–10 hr low) and BBQ sauce added after cooking." },
    title: "BBQ Pulled Pork",
    cuisine: "Comfort",
    blurb: "A dry rub (overnight if you have time), cooked until tender, then tossed with a certified-GF BBQ sauce.",
    best: "Either",
    prep: "15 min (+ optional overnight rub)",
    ipTotal: "~1 hr 45 min",
    scTotal: "8–10 hr on low",
    gf: [
      "BBQ sauce: many contain malt vinegar, soy sauce or wheat thickeners. Use a GF-labeled brand. Stubb's is labeled GF, but read the label every time.",
      "Buns: must be GF. Toast them on a clean pan or in a GF-only toaster.",
      "Use apple cider vinegar or plain distilled vinegar. Malt vinegar is not GF.",
    ],
    ingredients: [
      { title: "Pork & rub", items: [
        { q: 2.5, u: "lb", n: "boneless pork shoulder (butt)", prep: "cut in 4 chunks", a: M },
        { q: 2, u: "tbsp", n: "brown sugar", a: SP },
        { q: 1, u: "tbsp", n: "smoked paprika", a: SP },
        { q: 1, u: "tsp", n: "garlic powder", a: SP },
        { q: 1, u: "tsp", n: "onion powder", a: SP },
        { q: 2, u: "tsp", n: "kosher salt", a: ST },
        { q: 1, u: "tsp", n: "black pepper", a: ST },
      ]},
      { title: "Cooking liquid & sauce", items: [
        { q: 1, u: "cup", n: "apple juice", a: C },
        { q: 2, u: "tbsp", n: "apple cider vinegar", a: S },
        { q: 1, u: "cup", n: "BBQ sauce", gf: true, a: S },
      ]},
      { title: "To serve", items: [
        { q: 4, u: "", n: "hamburger bun (GF)", pl: "hamburger buns (GF)", gf: true, a: B },
        { q: 1, u: "bag", n: "coleslaw mix", opt: true, a: P },
      ]},
    ],
    ip: [
      "Mix the brown sugar, paprika, garlic powder, onion powder, salt and pepper, and rub it all over the pork. If you have time, cover and refrigerate overnight.",
      "Pour the apple juice, vinegar and <strong>½ cup water</strong> into the pot, then add the pork.",
      "Seal and cook on <strong>High Pressure 60 min</strong>, then <strong>natural release 15 min</strong>.",
      "Move the pork to a bowl, shred it, and discard any big pieces of fat. Skim the fat off the liquid.",
      "Toss the pork with the BBQ sauce and about ½ cup of the cooking liquid. <em>Add BBQ sauce only after pressure cooking. Thick, sugary sauce under pressure causes the Burn notice.</em>",
      "Optional: spread the pork on a sheet pan and broil 3–4 min for crispy edges.",
    ],
    sc: [
      "Rub the pork as above (overnight is optional).",
      "Add the apple juice and vinegar (no extra water) to the slow cooker, then the pork.",
      "Cook on <strong>low 8–10 hr</strong> (or high 5–6 hr) until it shreds easily.",
      "Shred the pork, skim the liquid, and toss with the BBQ sauce and a splash of the juices.",
    ],
    serve: "Serve on GF buns with coleslaw, or over baked potatoes.",
    leftovers: "Excellent for day-2 lunch. It also freezes well in portions with a little of the juice.",
  },

  {
    id: "beef-bean-chili",
    source: { name: "Kristine's Kitchen", url: "https://kristineskitchenblog.com/instant-pot-chili/", note: "Same timing (15 min + 10 min natural release) and the same tomatoes-on-top trick." },
    title: "Beef & Bean Chili",
    cuisine: "Comfort",
    blurb: "A classic, medium-mild chili. It's good on day one and even better on day two.",
    best: "Either",
    prep: "20 min",
    ipTotal: "~50 min",
    scTotal: "6–8 hr on low",
    gf: [
      "Chili powder: blends can include anti-caking agents or fillers. Buy one labeled GF, or a single-chile powder like ancho.",
      "Beef broth: labeled GF.",
      "Tortilla chips for topping: use chips labeled GF.",
    ],
    ingredients: [
      { title: "", items: [
        { q: 1, u: "lb", n: "ground beef (85/15)", a: M },
        { q: 1, u: "", n: "yellow onion", prep: "diced", a: P },
        { q: 1, u: "", n: "red bell pepper", prep: "diced", a: P },
        { q: 3, u: "clove", n: "garlic", prep: "minced", a: P },
        { q: 2, u: "tbsp", n: "chili powder", gf: true, a: SP },
        { q: 1.5, u: "tsp", n: "ground cumin", a: SP },
        { q: 1, u: "tsp", n: "smoked paprika", a: SP },
        { q: 0.5, u: "tsp", n: "dried oregano", a: SP },
        { q: 1, u: "tsp", n: "kosher salt", a: ST },
        { q: 1, u: "cup", n: "beef broth", gf: true, a: C },
        { q: 1, u: "can", sz: "15 oz", n: "kidney beans", prep: "drained & rinsed", a: C },
        { q: 1, u: "can", sz: "15 oz", n: "black beans", prep: "drained & rinsed", a: C },
        { q: 1, u: "can", sz: "14.5 oz", n: "diced tomatoes", a: C },
        { q: 1, u: "can", sz: "8 oz", n: "tomato sauce", a: C },
      ]},
      { title: "Toppings", items: [
        { q: null, u: "", n: "shredded cheddar", a: D },
        { q: null, u: "", n: "sour cream", a: D },
        { q: null, u: "", n: "green onion", a: P },
        { q: null, u: "", n: "tortilla chips (GF)", gf: true, a: B, opt: true },
      ]},
    ],
    ip: [
      "Set to Sauté. Brown the beef with the onion and bell pepper, 6–7 min, breaking it up as it cooks. Drain the excess fat.",
      "Stir in the garlic and all the spices and salt for 1 min.",
      "Pour in the broth and <strong>scrape the bottom clean</strong>. Add the beans.",
      "Pour the diced tomatoes and tomato sauce on top and <strong>do not stir</strong>. Tomatoes on the bottom can trigger the Burn notice.",
      "Seal and cook on <strong>High Pressure 15 min</strong>, then <strong>natural release 10 min</strong>.",
      "Stir. For thicker chili, simmer on Sauté 5 min.",
    ],
    sc: [
      "Brown the beef, onion and pepper in a skillet and drain the fat.",
      "Add to the slow cooker with everything else and stir.",
      "Cook on <strong>low 6–8 hr</strong> (or high 3–4 hr).",
    ],
    serve: "Top with cheese, sour cream and green onions. GF tortilla chips on the side are good for scooping.",
    leftovers: "Freezes very well. You can also serve day two over a baked potato.",
  },

  // ───────────────────────────── ITALIAN ─────────────────────────────
  {
    id: "tuscan-chicken",
    source: { name: "Amy + Jacky (Pressure Cook Recipes)", url: "https://www.pressurecookrecipes.com/instant-pot-tuscan-chicken/", note: "Timing matches theirs (thighs 5 min, breasts 4 min, 10 min natural release). Theirs adds <strong>soy sauce</strong>, which we left out." },
    title: "Creamy Tuscan Chicken",
    cuisine: "Italian",
    blurb: "Chicken in a garlicky cream sauce with sun-dried tomatoes, spinach and parmesan.",
    best: "Instant Pot",
    prep: "15 min",
    ipTotal: "~35 min",
    scTotal: "3–4 hr on low",
    gf: [
      "Chicken broth: labeled GF.",
      "GF pasta: cook it in a clean pot with fresh water, and drain in a colander that's been washed well (or a GF-only one). Never share pasta water with regular pasta.",
    ],
    ingredients: [
      { title: "", items: [
        { q: 1.5, u: "lb", n: "boneless skinless chicken thighs", prep: "or breasts, halved into thinner cutlets", a: M },
        { q: 1, u: "tsp", n: "Italian seasoning", a: SP },
        { q: 1, u: "tsp", n: "kosher salt", a: ST },
        { q: 0.5, u: "tsp", n: "black pepper", a: ST },
        { q: 1, u: "tbsp", n: "olive oil", a: ST },
        { q: 4, u: "clove", n: "garlic", prep: "minced", a: P },
        { q: 0.5, u: "cup", n: "sun-dried tomatoes in oil", prep: "chopped", a: C },
        { q: 1.5, u: "cup", n: "chicken broth", gf: true, a: C },
        { q: 0.75, u: "cup", n: "heavy cream", a: D },
        { q: 1.5, u: "tbsp", n: "cornstarch", a: SP },
        { q: 0.5, u: "cup", n: "grated parmesan", a: D },
        { q: 3, u: "cup", n: "baby spinach", a: P },
      ]},
      { title: "To serve", items: [
        { q: 8, u: "oz", n: "GF pasta (penne or rotini)", gf: true, a: G },
      ]},
    ],
    ip: [
      "Season the chicken with the Italian seasoning, salt and pepper.",
      "Set to Sauté. Add oil and sear the chicken 2–3 min per side. This is optional but adds flavor. Remove it.",
      "Add the garlic and sun-dried tomatoes for 1 min, then pour in the broth and <strong>scrape the bottom clean</strong>.",
      "Return the chicken. Seal and cook on <strong>High Pressure 5 min</strong> (4 min for breast cutlets), then <strong>natural release 10 min</strong>.",
      "Take the chicken out. Set to Sauté, whisk the cream and cornstarch together, stir in, and simmer 2 min until thick.",
      "Turn off the heat and stir in the parmesan and spinach until wilted. Slice the chicken and return it to the sauce.",
      "Meanwhile, cook the GF pasta on the stove.",
    ],
    sc: [
      "Put the seasoned chicken, broth, garlic and sun-dried tomatoes in the slow cooker.",
      "Cook on <strong>low 3–4 hr</strong> until the chicken reaches 165 °F. <em>A small load in a big crock cooks fast, so check at 3 hr.</em>",
      "Remove the chicken. Stir in the cream whisked with the cornstarch, then the parmesan and spinach. Cover on high 15 min.",
      "Slice the chicken, return it to the sauce, and serve over GF pasta.",
    ],
    serve: "Serve over GF pasta or rice, or with roasted potatoes.",
    leftovers: "Reheat gently with a splash of broth. It makes a great next-day lunch over fresh GF pasta.",
  },

  {
    id: "sausage-peppers-polenta",
    source: { name: "Wholesome Yum", url: "https://www.wholesomeyum.com/slow-cooker-sausage-and-peppers/", note: "Theirs: browned sausages, 4–5 hr low / 2–3 hr high. Polenta is our addition." },
    title: "Sausage & Peppers over Creamy Polenta",
    cuisine: "Italian",
    blurb: "Italian sausage, sweet peppers and marinara, spooned over parmesan polenta.",
    best: "Slow Cooker",
    prep: "15 min",
    ipTotal: "~35 min",
    scTotal: "4–6 hr on low",
    gf: [
      "Italian sausage: some brands use wheat fillers or breadcrumbs. <strong>Buy sausage labeled GF</strong>. Many major brands are.",
      "Marinara: most jarred sauces are GF, but check the label.",
      "Polenta / corn grits: cornmeal is often milled alongside wheat. Buy one labeled GF (e.g. Bob's Red Mill GF corn grits/polenta), or a pre-cooked polenta tube labeled GF.",
    ],
    ingredients: [
      { title: "Sausage & peppers", items: [
        { q: 1.25, u: "lb", n: "Italian sausage links (mild)", gf: true, a: M },
        { q: 2, u: "", n: "bell pepper (any color)", pl: "bell peppers (any color)", prep: "sliced in strips", a: P },
        { q: 1, u: "", n: "yellow onion", prep: "sliced", a: P },
        { q: 3, u: "clove", n: "garlic", prep: "minced", a: P },
        { q: 1, u: "jar", sz: "24 oz", n: "marinara sauce", gf: true, a: C },
        { q: 1, u: "tsp", n: "Italian seasoning", a: SP },
      ]},
      { title: "Polenta", items: [
        { q: 1, u: "cup", n: "polenta / corn grits (GF)", gf: true, a: G },
        { q: 2, u: "tbsp", n: "butter", a: D },
        { q: 0.5, u: "cup", n: "grated parmesan", a: D },
        { q: 1, u: "tsp", n: "kosher salt", a: ST },
      ]},
    ],
    ip: [
      "Set to Sauté and brown the sausages 4–5 min. Remove them.",
      "Pour in <strong>1 cup water</strong> and scrape the bottom clean.",
      "Add the peppers, onion, garlic and Italian seasoning, and set the sausages on top.",
      "Pour the marinara over everything and <strong>do not stir</strong>.",
      "Seal and cook on <strong>High Pressure 8 min</strong>, then quick release. Stir, and simmer on Sauté 5 min to thicken.",
      "Polenta (stovetop, 20 min): bring 4 cups salted water to a boil, slowly whisk in the polenta, and cook on low 15–20 min, stirring often. Finish with the butter and parmesan.",
    ],
    sc: [
      "For more flavor, brown the sausages in a skillet 5 min. This is optional.",
      "Put the peppers, onion and garlic in the bottom, the sausages on top, then pour over the marinara, <strong>½ cup water</strong> and the Italian seasoning.",
      "Cook on <strong>low 4–6 hr</strong> (or high 2–3 hr). A big crock with a small load runs hot, so check at 4 hr.",
      "In the last 20 min, make the polenta on the stove: whisk it into 4 cups boiling salted water, cook on low 15–20 min stirring often, then stir in the butter and parmesan.",
    ],
    serve: "Serve over polenta, or over GF pasta if you'd rather.",
    leftovers: "Leftover polenta sets firm. Slice it and pan-fry it in butter, or eat the sausage and peppers on a GF roll.",
  },

  {
    id: "zuppa-toscana",
    source: { name: "Jo Cooks", url: "https://www.jocooks.com/recipes/instant-pot-zuppa-toscana/", note: "Same 5 min pressure time. Theirs uses cubed potatoes and a 10 min natural release; our thin slices only need a quick release." },
    title: "Zuppa Toscana",
    cuisine: "Italian",
    blurb: "An Olive Garden–style soup with sausage, potatoes and kale in a creamy broth. Naturally gluten free if you check the sausage and broth.",
    best: "Instant Pot",
    prep: "20 min",
    ipTotal: "~40 min",
    scTotal: "6–7 hr on low",
    gf: [
      "Italian sausage: labeled GF (some use wheat fillers).",
      "Bacon: most plain bacon is GF, but check. Avoid flavored or glazed kinds.",
      "Chicken broth: labeled GF.",
    ],
    ingredients: [
      { title: "", items: [
        { q: 1, u: "lb", n: "bulk Italian sausage", prep: "mild or hot", gf: true, a: M },
        { q: 4, u: "slice", n: "bacon", opt: true, gf: true, a: M },
        { q: 1, u: "", n: "yellow onion", prep: "diced", a: P },
        { q: 3, u: "clove", n: "garlic", prep: "minced", a: P },
        { q: 1.5, u: "lb", n: "russet potatoes", prep: "about 3, halved & sliced ¼ inch", a: P },
        { q: 4, u: "cup", n: "chicken broth", gf: true, a: C },
        { q: 0.25, u: "tsp", n: "red pepper flakes", opt: true, a: SP },
        { q: 1, u: "bunch", n: "kale", prep: "stems removed, chopped (~3 cups)", a: P },
        { q: 0.75, u: "cup", n: "heavy cream", a: D },
        { q: null, u: "", n: "grated parmesan", prep: "for topping", a: D },
      ]},
    ],
    ip: [
      "If using bacon: Sauté until crisp, remove, crumble, and pour off most of the fat.",
      "Brown the sausage 5–6 min, breaking it up. Drain any excess fat.",
      "Add the onion for 3 min, then the garlic and pepper flakes for 30 sec.",
      "Pour in the broth and <strong>scrape the bottom clean</strong>, then add the potatoes.",
      "Seal and cook on <strong>High Pressure 5 min</strong>, then quick release.",
      "Set to Sauté, stir in the kale and cook 2–3 min until wilted. Turn off the heat and stir in the cream.",
    ],
    sc: [
      "Brown the sausage (and bacon, if using) and the onion in a skillet, then drain.",
      "Add to the slow cooker with the garlic, pepper flakes, potatoes and broth.",
      "Cook on <strong>low 6–7 hr</strong> (or high 3–4 hr) until the potatoes are tender.",
      "Stir in the kale and cream and cook on high 20–30 min.",
    ],
    serve: "Top with the bacon and parmesan.",
    leftovers: "Reheats well for 2–3 days. Freezing isn't recommended because cream-and-potato soups get grainy.",
  },

  {
    id: "chicken-cacciatore",
    source: { name: "Skinnytaste", url: "https://www.skinnytaste.com/instant-pot-chicken-cacciatore/", note: "Same method. Theirs cooks bone-in thighs 25 min for fall-off-the-bone meat. Other sites use 8–12 min; ours is 15." },
    title: "Chicken Cacciatore",
    cuisine: "Italian",
    blurb: "\"Hunter's chicken\": bone-in thighs braised with peppers, mushrooms, tomatoes and a splash of red wine.",
    best: "Either",
    prep: "20 min",
    ipTotal: "~50 min",
    scTotal: "5–6 hr on low",
    gf: [
      "This dish is naturally gluten free. Watch the <strong>chicken broth</strong> (labeled GF) and whatever you serve it over.",
      "Wine is gluten free.",
      "Don't dredge the chicken in flour like some traditional recipes do. Season and sear it plain.",
    ],
    ingredients: [
      { title: "", items: [
        { q: 2, u: "lb", n: "bone-in skin-on chicken thighs", prep: "about 4", a: M },
        { q: 1.5, u: "tsp", n: "kosher salt", a: ST },
        { q: 0.5, u: "tsp", n: "black pepper", a: ST },
        { q: 1, u: "tbsp", n: "olive oil", a: ST },
        { q: 1, u: "", n: "yellow onion", prep: "sliced", a: P },
        { q: 1, u: "", n: "red bell pepper", prep: "sliced", a: P },
        { q: 8, u: "oz", n: "cremini mushrooms", prep: "sliced", a: P },
        { q: 4, u: "clove", n: "garlic", prep: "minced", a: P },
        { q: 2, u: "tbsp", n: "tomato paste", a: C },
        { q: 0.5, u: "cup", n: "dry red wine", prep: "or more broth", a: S },
        { q: 0.75, u: "cup", n: "chicken broth", gf: true, a: C },
        { q: 1.5, u: "tsp", n: "Italian seasoning", a: SP },
        { q: 1, u: "can", sz: "14.5 oz", n: "diced tomatoes", a: C },
        { q: null, u: "", n: "fresh parsley or basil", a: P, opt: true },
      ]},
      { title: "To serve", items: [
        { q: 8, u: "oz", n: "GF pasta (penne or rotini)", gf: true, a: G, opt: true },
      ]},
    ],
    ip: [
      "Season the chicken with salt and pepper. Set to Sauté (High), add oil, and sear the thighs <strong>skin-side down</strong> 5 min until golden. Remove.",
      "Pour off all but 1 tbsp of fat. Cook the onion, pepper and mushrooms 4 min, then the garlic and tomato paste for 1 min.",
      "Add the wine and <strong>scrape the bottom clean</strong>. Simmer 1 min, then add the broth and Italian seasoning.",
      "Set the chicken on top, skin-side up, and pour the tomatoes over without stirring.",
      "Seal and cook on <strong>High Pressure 15 min</strong>, then <strong>natural release 10 min</strong>.",
      "Take the chicken out and simmer the sauce on Sauté 5 min to thicken. Top with herbs.",
    ],
    sc: [
      "Sear the seasoned thighs skin-side down in a skillet. The skin softens in a slow cooker anyway, so you can remove it if you like.",
      "Put the onion, pepper, mushrooms and garlic in the slow cooker with the chicken on top.",
      "Whisk the tomatoes, tomato paste, wine, broth and Italian seasoning together and pour over.",
      "Cook on <strong>low 5–6 hr</strong> (or high 3 hr).",
    ],
    serve: "Serve over GF pasta, polenta (see Sausage & Peppers) or rice.",
    leftovers: "Pull the meat off the bones and toss it with the sauce and GF pasta for lunch.",
  },

  // ───────────────────────────── MEXICAN ─────────────────────────────
  {
    id: "salsa-verde-chicken",
    source: { name: "Inspired Taste", url: "https://www.inspiredtaste.net/36315/instant-pot-salsa-verde-chicken-recipe/", note: "Theirs: 1 lb chicken in 2 cups salsa verde, 8 min + 5 min natural release. Ours has 50% more chicken, so it cooks a bit longer." },
    title: "Salsa Verde Chicken Tacos",
    cuisine: "Mexican",
    blurb: "The easiest recipe here: chicken plus a jar of salsa verde gives you shredded taco filling in about 30 minutes.",
    best: "Either",
    prep: "10 min",
    ipTotal: "~35 min",
    scTotal: "4–5 hr on low",
    gf: [
      "Corn tortillas: <strong>not all are 100% corn</strong>, and many are made alongside flour tortillas. Buy ones labeled GF.",
      "Salsa verde: usually GF, but check the label.",
      "Warm the tortillas in a clean skillet or directly over a gas flame, never on a pan used for flour tortillas.",
    ],
    ingredients: [
      { title: "", items: [
        { q: 1.5, u: "lb", n: "boneless skinless chicken thighs", a: M },
        { q: 1, u: "jar", sz: "16 oz", n: "salsa verde (mild)", gf: true, a: C },
        { q: 0.5, u: "cup", n: "chicken broth", gf: true, a: C },
        { q: 1, u: "tsp", n: "ground cumin", a: SP },
        { q: 0.5, u: "tsp", n: "garlic powder", a: SP },
        { q: 1, u: "tsp", n: "kosher salt", a: ST },
        { q: 1, u: "", n: "lime", a: P },
      ]},
      { title: "To serve", items: [
        { q: 12, u: "", n: "corn tortilla (GF)", pl: "corn tortillas (GF)", gf: true, a: B },
        { q: null, u: "", n: "cilantro", a: P },
        { q: 1, u: "", n: "avocado", a: P },
        { q: null, u: "", n: "white onion", prep: "diced", a: P },
        { q: null, u: "", n: "cotija or queso fresco", a: D },
        { q: null, u: "", n: "sour cream", a: D, opt: true },
      ]},
    ],
    ip: [
      "Pour the broth into the pot, add the chicken, and sprinkle with the cumin, garlic powder and salt.",
      "Pour the salsa verde over the top.",
      "Seal and cook on <strong>High Pressure 10 min</strong>, then <strong>natural release 10 min</strong>.",
      "Shred the chicken right in the pot with two forks, squeeze in the lime, and stir so it soaks up the sauce.",
    ],
    sc: [
      "Put everything except the lime in the slow cooker.",
      "Cook on <strong>low 4–5 hr</strong> (or high 2–3 hr).",
      "Shred the chicken in the sauce and add the lime juice.",
    ],
    serve: "Serve in warm GF corn tortillas with onion, cilantro, avocado and cotija.",
    leftovers: "Use it in rice bowls, nachos on GF chips, or baked in GF corn-tortilla enchiladas.",
  },

  {
    id: "pork-carnitas",
    source: { name: "Pressure Cooking Today", url: "https://www.pressurecookingtoday.com/pork-carnitas-in-the-pressure-cooker/", note: "Theirs: 1-inch cubes, 30 min + 10 min natural release, orange juice base. Our chunks are larger (2-inch), so 35 min." },
    title: "Crispy Pork Carnitas",
    cuisine: "Mexican",
    blurb: "Citrus-braised pork shoulder, shredded, then broiled until crisp at the edges.",
    best: "Either",
    prep: "15 min (+ optional overnight rub)",
    ipTotal: "~1 hr 30 min",
    scTotal: "8–10 hr on low",
    gf: [
      "Chili powder: labeled GF, or use ancho chile powder.",
      "Chicken broth: labeled GF.",
      "Corn tortillas: labeled GF (see Salsa Verde Chicken).",
    ],
    ingredients: [
      { title: "", items: [
        { q: 2.5, u: "lb", n: "boneless pork shoulder (butt)", prep: "cut in 2-inch chunks", a: M },
        { q: 2, u: "tsp", n: "kosher salt", a: ST },
        { q: 1, u: "tsp", n: "ground cumin", a: SP },
        { q: 1, u: "tsp", n: "dried oregano", a: SP },
        { q: 0.5, u: "tsp", n: "chili powder", gf: true, a: SP },
        { q: 0.5, u: "tsp", n: "black pepper", a: ST },
        { q: 1, u: "", n: "yellow onion", prep: "quartered", a: P },
        { q: 4, u: "clove", n: "garlic", prep: "smashed", a: P },
        { q: 1, u: "", n: "orange", prep: "juiced, keep the halves", a: P },
        { q: 2, u: "", n: "lime", prep: "juiced", a: P },
        { q: 0.75, u: "cup", n: "chicken broth", gf: true, a: C },
        { q: 1, u: "", n: "bay leaf", pl: "bay leaves", a: SP },
      ]},
      { title: "To serve", items: [
        { q: 12, u: "", n: "corn tortilla (GF)", pl: "corn tortillas (GF)", gf: true, a: B },
        { q: null, u: "", n: "cilantro", a: P },
        { q: null, u: "", n: "white onion", prep: "diced", a: P },
        { q: null, u: "", n: "salsa", gf: true, a: C, opt: true },
      ]},
    ],
    ip: [
      "Toss the pork with the salt, cumin, oregano, chili powder and pepper. If you have time, cover and refrigerate overnight.",
      "Pour the broth, orange juice and lime juice into the pot. Add the onion, garlic, bay leaf, pork and the squeezed orange halves.",
      "Seal and cook on <strong>High Pressure 35 min</strong>, then <strong>natural release 15 min</strong>.",
      "Discard the onion, orange halves and bay leaf, and shred the pork.",
      "<strong>Crisp it:</strong> spread the pork on a foil-lined sheet pan, drizzle with ½ cup of the cooking liquid, and broil on high 4–6 min until the edges are browned and crispy.",
    ],
    sc: [
      "Season the pork as above (overnight is optional).",
      "Add everything to the slow cooker, using only <strong>½ cup broth</strong>.",
      "Cook on <strong>low 8–10 hr</strong> (or high 5–6 hr).",
      "Shred, then broil on a sheet pan with a drizzle of the juices as above.",
    ],
    serve: "Serve in GF corn tortillas with onion, cilantro and salsa, or over rice with black beans.",
    leftovers: "Re-crisp in a hot skillet. It makes excellent burrito bowls. Freeze extra with a little of the juice.",
  },

  {
    id: "chicken-tortilla-soup",
    source: { name: "Kristine's Kitchen", url: "https://kristineskitchenblog.com/instant-pot-chicken-tortilla-soup/", note: "Theirs: 9 min + 10 min natural release; slow cooker 6–8 hr low. Timing matches." },
    title: "Chicken Tortilla Soup",
    cuisine: "Mexican",
    blurb: "A brothy, lightly spiced soup with black beans and corn, piled with toppings.",
    best: "Either",
    prep: "15 min",
    ipTotal: "~40 min",
    scTotal: "6 hr on low",
    gf: [
      "Tortilla chips or strips: must be labeled GF.",
      "Chicken broth and chili powder: labeled GF.",
      "Don't use canned enchilada sauce as a shortcut. Many contain wheat flour.",
    ],
    ingredients: [
      { title: "", items: [
        { q: 1.25, u: "lb", n: "boneless skinless chicken breasts", prep: "or thighs", a: M },
        { q: 1, u: "tbsp", n: "olive oil", a: ST },
        { q: 1, u: "", n: "yellow onion", prep: "diced", a: P },
        { q: 1, u: "", n: "jalapeño", prep: "seeded & minced", opt: true, a: P },
        { q: 3, u: "clove", n: "garlic", prep: "minced", a: P },
        { q: 1.5, u: "tsp", n: "ground cumin", a: SP },
        { q: 1, u: "tsp", n: "chili powder", gf: true, a: SP },
        { q: 0.5, u: "tsp", n: "dried oregano", a: SP },
        { q: 1, u: "tsp", n: "kosher salt", a: ST },
        { q: 4, u: "cup", n: "chicken broth", gf: true, a: C },
        { q: 1, u: "can", sz: "15 oz", n: "black beans", prep: "drained & rinsed", a: C },
        { q: 1, u: "can", sz: "10 oz", n: "diced tomatoes & green chiles (mild)", a: C },
        { q: 1, u: "cup", n: "frozen corn", a: F },
        { q: 1, u: "", n: "lime", a: P },
      ]},
      { title: "Toppings", items: [
        { q: null, u: "", n: "tortilla chips (GF)", gf: true, a: B },
        { q: 1, u: "", n: "avocado", a: P },
        { q: null, u: "", n: "shredded Monterey Jack", a: D },
        { q: null, u: "", n: "sour cream", a: D },
        { q: null, u: "", n: "cilantro", a: P },
      ]},
    ],
    ip: [
      "Set to Sauté. Add oil and cook the onion and jalapeño 3 min. Add the garlic and spices for 30 sec.",
      "Pour in the broth and <strong>scrape the bottom clean</strong>.",
      "Add the chicken, beans and corn, then pour the tomatoes on top.",
      "Seal and cook on <strong>High Pressure 10 min</strong>, then <strong>natural release 10 min</strong>.",
      "Shred the chicken in the pot and squeeze in the lime.",
    ],
    sc: [
      "Add everything except the lime to the slow cooker.",
      "Cook on <strong>low 6 hr</strong> (or high 3 hr).",
      "Shred the chicken and add the lime juice.",
    ],
    serve: "Top with crushed GF chips, avocado, cheese, sour cream and cilantro.",
    leftovers: "Even better the next day, and it freezes well. Keep the chips separate so they stay crunchy.",
  },

  // ───────────────────────────── ASIAN ─────────────────────────────
  {
    id: "mongolian-beef",
    source: { name: "Pressure Cooking Today", url: "https://www.pressurecookingtoday.com/pressure-cooker-mongolian-beef/", note: "Same 12 min + quick release and cornstarch finish. Theirs uses <strong>regular soy sauce</strong> (not GF) and twice the sugar." },
    title: "Mongolian Beef",
    cuisine: "Asian",
    blurb: "Tender flank steak in a glossy sweet-savory garlic and ginger sauce. Better than takeout, and safe.",
    best: "Instant Pot",
    prep: "20 min",
    ipTotal: "~30 min",
    scTotal: "4–5 hr on low",
    gf: [
      "<strong>Regular soy sauce contains wheat.</strong> Use tamari labeled GF (e.g. San-J, Kikkoman GF). Some tamari still contains wheat, so read the label. Coconut aminos also work.",
      "Restaurant Mongolian beef is almost never GF. It's usually dredged in flour and made with soy sauce.",
    ],
    ingredients: [
      { title: "", items: [
        { q: 1.5, u: "lb", n: "flank steak", prep: "sliced thin against the grain", a: M },
        { q: 1, u: "tbsp", n: "neutral oil", a: ST },
        { q: 4, u: "clove", n: "garlic", prep: "minced", a: P },
        { q: 1, u: "tbsp", n: "fresh ginger", prep: "grated", a: P },
        { q: 0.5, u: "cup", n: "GF tamari (reduced sodium)", gf: true, a: S },
        { q: 1/3, u: "cup", n: "brown sugar", prep: "packed", a: SP },
        { q: 3, u: "tbsp", n: "cornstarch", a: SP },
        { q: 1, u: "tsp", n: "toasted sesame oil", a: S },
        { q: 4, u: "", n: "green onion", prep: "cut in 1-inch pieces", a: P },
      ]},
      { title: "To serve", items: [
        { q: 1.5, u: "cup", n: "jasmine rice", a: G },
        { q: 1, u: "lb", n: "broccoli florets", a: P },
      ]},
    ],
    ip: [
      "Tip: freeze the steak for 20–30 min first so it's easy to slice thin.",
      "Set to Sauté. Add oil, garlic and ginger for 30 sec.",
      "Add <strong>1 cup water</strong>, the tamari and brown sugar. Stir to dissolve and scrape the bottom.",
      "Add the beef and stir to coat. Seal and cook on <strong>High Pressure 12 min</strong>, then quick release.",
      "Set to Sauté. Whisk the cornstarch with 3 tbsp cold water, stir it in, and simmer 1–2 min until glossy and thick.",
      "Stir in the green onions and sesame oil.",
    ],
    sc: [
      "Toss the sliced beef with the cornstarch and put it in the slow cooker.",
      "Whisk together the tamari, brown sugar, garlic, ginger and <strong>½ cup water</strong>, and pour over.",
      "Cook on <strong>low 4–5 hr</strong> (or high 2–3 hr), stirring once if you're home.",
      "Stir in the green onions and sesame oil.",
    ],
    serve: "Serve over jasmine rice with steamed broccoli.",
    leftovers: "Reheats well. Use leftovers in GF fried rice with an egg.",
  },

  {
    id: "honey-garlic-chicken",
    source: { name: "Pressure Cooking Today", url: "https://www.pressurecookingtoday.com/spicy-honey-garlic-chicken-in-the-pressure-cooker/", note: "Theirs: boneless thighs, 9 min + quick release, honey/ketchup/<strong>soy sauce</strong> (swapped for tamari here)." },
    title: "Honey Garlic Chicken",
    cuisine: "Asian",
    blurb: "Sticky, sweet and garlicky. Mostly dumping things in a pot, and a family favorite.",
    best: "Either",
    prep: "10 min",
    ipTotal: "~30 min",
    scTotal: "4 hr on low",
    gf: [
      "Tamari labeled GF in place of soy sauce.",
      "Ketchup: Heinz is labeled GF. Check any other brand.",
      "Rice vinegar is GF. Avoid malt vinegar.",
    ],
    ingredients: [
      { title: "", items: [
        { q: 1.5, u: "lb", n: "boneless skinless chicken thighs", a: M },
        { q: 1/3, u: "cup", n: "honey", a: S },
        { q: 1/3, u: "cup", n: "GF tamari (reduced sodium)", gf: true, a: S },
        { q: 0.25, u: "cup", n: "ketchup", gf: true, a: S },
        { q: 1, u: "tbsp", n: "rice vinegar", a: S },
        { q: 5, u: "clove", n: "garlic", prep: "minced", a: P },
        { q: 1, u: "tsp", n: "fresh ginger", prep: "grated", a: P },
        { q: 2, u: "tbsp", n: "cornstarch", a: SP },
        { q: 2, u: "", n: "green onion", prep: "sliced", a: P },
        { q: null, u: "", n: "sesame seeds", a: SP, opt: true },
      ]},
      { title: "To serve", items: [
        { q: 1.5, u: "cup", n: "jasmine rice", a: G },
        { q: 1, u: "lb", n: "broccoli florets", prep: "or green beans", a: P },
      ]},
    ],
    ip: [
      "Whisk the honey, tamari, ketchup, vinegar, garlic, ginger and <strong>¾ cup water</strong> right in the pot.",
      "Add the chicken and turn it to coat.",
      "Seal and cook on <strong>High Pressure 10 min</strong>, then <strong>natural release 5 min</strong>.",
      "Take the chicken out and cut it into bite-size pieces.",
      "Set to Sauté. Whisk the cornstarch with 3 tbsp cold water, stir it in, and simmer 1–2 min until sticky. Return the chicken.",
      "Top with green onions and sesame seeds.",
    ],
    sc: [
      "Whisk the sauce ingredients with only <strong>¼ cup water</strong> in the slow cooker and add the chicken.",
      "Cook on <strong>low 4 hr</strong> (or high 2 hr).",
      "Take the chicken out and cut it up. Stir in the cornstarch slurry and cook on high 15 min until thick (or reduce the sauce in a saucepan).",
      "Return the chicken and garnish.",
    ],
    serve: "Serve over rice with steamed broccoli or green beans.",
    leftovers: "A good next-day lunch bowl. Add a splash of water when reheating.",
  },

  {
    id: "thai-red-curry",
    source: { name: "Paint the Kitchen Red", url: "https://www.paintthekitchenred.com/instant-pot-thai-red-curry/", note: "Theirs: 4 min + quick release with thinly sliced chicken, veg added after. Our 1-inch pieces get 5 min + a short natural release." },
    title: "Thai Red Curry Chicken",
    cuisine: "Asian",
    blurb: "Coconut red curry with chicken, bell pepper and peas. Mild with 2 tbsp of paste, medium with 3.",
    best: "Instant Pot",
    prep: "15 min",
    ipTotal: "~30 min",
    scTotal: "4 hr on low",
    gf: [
      "Red curry paste: Thai Kitchen is labeled GF and on the mild side. Check other brands.",
      "Fish sauce: some brands add wheat or hydrolyzed wheat protein. Red Boat (anchovy + salt) is GF, or use GF tamari.",
      "Chicken broth: labeled GF.",
    ],
    ingredients: [
      { title: "", items: [
        { q: 1.5, u: "lb", n: "boneless skinless chicken thighs", prep: "1-inch pieces", a: M },
        { q: 1, u: "tbsp", n: "neutral oil", a: ST },
        { q: 1, u: "", n: "yellow onion", prep: "sliced", a: P },
        { q: 3, u: "clove", n: "garlic", prep: "minced", a: P },
        { q: 1, u: "tbsp", n: "fresh ginger", prep: "grated", a: P },
        { q: 2, u: "tbsp", n: "red curry paste", prep: "3 for medium heat", gf: true, a: S },
        { q: 0.5, u: "cup", n: "chicken broth", gf: true, a: C },
        { q: 1, u: "can", sz: "13.5 oz", n: "full-fat coconut milk", a: C },
        { q: 1, u: "tbsp", n: "fish sauce", gf: true, a: S },
        { q: 1, u: "tbsp", n: "brown sugar", a: SP },
        { q: 1, u: "", n: "red bell pepper", prep: "sliced", a: P },
        { q: 1, u: "cup", n: "frozen peas", a: F },
        { q: 1, u: "", n: "lime", a: P },
        { q: null, u: "", n: "fresh basil or cilantro", a: P },
      ]},
      { title: "To serve", items: [
        { q: 1.5, u: "cup", n: "jasmine rice", a: G },
      ]},
    ],
    ip: [
      "Set to Sauté. Add oil and cook the onion 3 min. Add the garlic, ginger and curry paste and stir for 1 min until fragrant.",
      "Pour in the broth and <strong>scrape the bottom clean</strong>. This matters most with coconut milk.",
      "Add the chicken, fish sauce and brown sugar. Pour the coconut milk on top and <strong>do not stir</strong>.",
      "Seal and cook on <strong>High Pressure 5 min</strong>, then <strong>natural release 5 min</strong>.",
      "Set to Sauté. Add the bell pepper and peas and simmer 3–4 min. Finish with lime juice and herbs.",
    ],
    sc: [
      "Optional: fry the curry paste, garlic and ginger in a little oil in a skillet for 1 min to bloom the flavor.",
      "Add everything except the bell pepper, peas, lime and herbs to the slow cooker.",
      "Cook on <strong>low 4 hr</strong> (or high 2 hr).",
      "Add the bell pepper and peas for the last 30 min, then the lime and herbs.",
    ],
    serve: "Serve over jasmine rice.",
    leftovers: "It tastes even better on day two. Freezes OK, but the peppers soften.",
  },
];
